[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_vault = "AH4vTxcx557pVqWXsdXp9mqxb73SayXrb1gf9ugbWp9W"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
